### ISSUE TITLE
Use contrast to draw attention to controls

### ISSUE THREAD

**Issue by w33ble** [bradwestfall/questionable-issues#3]
Generally when you show an interface to a user, there will be one action that you'll want to encourage the user to take. You can use contrast to "highlight" that action. For example, here, you probably don't want to draw equal attention to both of these buttons:

![screenshot 2018-02-16 15 30 34](https://user-images.githubusercontent.com/404731/36332226-a2fa931c-132e-11e8-8d21-4f7c0d3cb630.png)

If your intention is to draw attention to one of the actions, make that one stand out by making the others more subtle.

![screenshot 2018-02-16 15 34 11](https://user-images.githubusercontent.com/404731/36332312-ebd2a700-132e-11e8-9cc3-2eba3646fcc3.png)

This is just one example, but it's a good thing to keep in mind throughout the app.

**Comment by bradwestfall** [comment]
I would generally agree, but when browsing questions of tests, I don't know what the user wants to do, so I don't know which of these things (linking or editing) is more important. Thoughts?

**Comment by w33ble** [comment]
> Thoughts?

I suspect using "unlink" is rare, and thus doesn't need attention. In fact, you could probably safely hide it in that dropdown on the edit button.

**Comment by bradwestfall** [comment]
Well, it depends. I find that with other systems when I want to link and unlink questions from a test that there usually aren't easy ways to do it, so it might not be a frequent thing but when it's needed, having it out front and not behind a dropdown menu of options is nice. It's certainly more needed on the page similar to this one where you're still in the test view context but looking at all questions. The main point of that page is to quickly link and unlink question bank questions to and from the test. So on this page you're showing of browsing just the test's questions, it's nice that the UI is consistent in the way you link and unlink. Although I think I might want to make the action look more like a toggle instead of a button, that would solve what you're saying about having two calls to action.

Btw, I know I'm still using link and unlink here, but the new term is Assign and Unassign since a lot of people found the term link confusing.

**Comment by bradwestfall** [comment]
The new planned UI (not live at the time of this writing)

![screen shot 2018-03-12 at 12 29 15 am](https://user-images.githubusercontent.com/2272118/37270575-8bd1a016-258c-11e8-8923-3aa4f0eace5d.png)
