### ISSUE TITLE
"changing questions" link in FAQ doesn't work

### ISSUE THREAD

**Issue by w33ble** [bradwestfall/questionable-issues#6]
Clicking on the link doesn't do anything. Maybe it was linking to a question that has been removed?

Link: https://app.questionable.io/faq#changing-questions-scores

**Comment by bradwestfall** [comment]
Thanks for finding and posting this @w33ble 

I'm wondering where you clicked a link. The only two places I can find my searching for `changing-questions-scores` is the target itself (the thing with id="changing-questions-scores") and one question right below it that had the anchor with the hash to go to the question above. I'm wondering if it did work and you didn't see a scroll just because they were close? In any case it works for me in Chrome and FF. Can you test again to confirm?

I did notice though that even though it works for me when the FAQ page is already loaded and I click a link to go to a question, it doesn't work if I refresh the page and I want the new page load to automatically drop down to the anchored question. If that's the only issue, I need to fix it eventually but for now I'll label this as low-priority

**Comment by w33ble** [comment]
The link is in this section: https://app.questionable.io/faq#removing-vs-unlinking-vs-deactivating-vs-archiving

**Comment by bradwestfall** [comment]
Yea, looking up the other night how to fix that seemed daunting. Thank you

**Comment by w33ble** [comment]
redux-first-router has a scroll restore thing, maybe that would lead to some solution? effectively you need to scroll to a position in `componentDidMount` instead of relying on the native browser functionality. SSR would also fix this.

**Comment by bradwestfall** [comment]
I tried, I worked for a bit on trying to get `window.scrollTo` to work from didMount but couldn't
